### ISSUE TITLE
How can I obtain interpretable equations from EQL as described in the paper?

### ISSUE THREAD

**Issue by Rafail-Karkanis** [KristofPusztai/EQL#1]
The paper discusses the acquisition of interpretable expressions from EQL, as illustrated in Fig. 5(e). However, I was unable to locate a way to do so. I have searched the files for occurrences of "sympy," but none were found. Also, there is no such example provided in README.md or the Jupyter notebook. Could you please help me in how to print these interpretable equations?

Thank you in advance.

**Comment by KristofPusztai** [comment]
Hello Rafail, I have not directly added in a method for showing the "interpretable expression" as presented in the paper as this expression can be recovered from the `.get_weights` method which shows the weights and biases of each layer (the interpretable expression is just these weights & biases along with the corresponding activation function). However, when the model becomes deeper (i.e. more than 2 layers) recovering the interpretable expression becomes quite complex.

I will try to implement a sympy method for printing out this interpretable expression programmatically in the next few weeks!

**Comment by KristofPusztai** [comment]
added in `formula` method for generating interpretable equations in [latest release](https://github.com/KristofPusztai/EQL/releases/tag/v2.1.0)

`pip install EQL-NN --upgrade` for latest version
